In [4]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

Using TensorFlow backend.


In [26]:
dataframe = pandas.read_csv("../data/files/test_set.csv", delimiter=',',error_bad_lines=False,compression='gzip')

xtest = dataframe.values
 
xtest=xtest[:,0:4]

In [29]:
xtest 

array([[ 0.78782268,         nan,  0.10434504,  0.57858404],
       [ 0.12527474,         nan,         nan,  0.6248561 ],
       [ 0.58223803,         nan,  0.53502828,  0.7276547 ],
       ..., 
       [ 0.43160473,         nan,  0.29190985,  0.01032999],
       [ 0.04497931,         nan,  0.82359407,  0.66296043],
       [ 0.16491328,         nan,  0.68592183,  0.35741933]])

In [21]:
dataframe = pandas.read_csv("../data/files/training_set.csv", delimiter=',',error_bad_lines=False,compression='gzip')
dataset = dataframe.values
 
X = dataset[2:,0:4]
Y = dataset[2:,3:4]

In [22]:
X[:4]

array([[ 2.        ,  0.70731618,  0.07063119,  0.35393478],
       [ 3.        ,  0.6658157 ,  0.07063119,  0.65333107],
       [ 4.        ,  0.37703471,  0.07063119,  0.44315752],
       [ 5.        ,  0.4958097 ,  0.07063119,  0.19724265]])

In [23]:
Y[:4]

array([[ 0.35393478],
       [ 0.65333107],
       [ 0.44315752],
       [ 0.19724265]])

In [ ]:
 
# define base model
def baseline_model():

    # create model
    model = Sequential()
    model.add(Dense(4, input_dim=4, init="normal", activation='relu'))#cantidad de entradas es el 4,inputdim
    model.add(Dense(1, init="normal"))#salida
    # Compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    
    
    return model

In [ ]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=3, batch_size=5, verbose=2)/#epocas cantidad de ciblos 100 tomaban 

    # round predictions


In [ ]:
kfold = KFold(n_splits=2, random_state=seed) #splits 5 o 10 
results = cross_val_score(estimator, X, Y, cv=kfold)

print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))
estimator.fit(X, Y)
prediction = estimator.predict(X)
 
# round predictionsrounded =
print(prediction) 
